repos:
  - repo: local
    hooks:
      - id: stylua
        name: stylua
        entry: stylua --config-path stylua.toml
        language: system
        types: [lua]
        files: ^CombatMode/.*\.lua$
        exclude: ^CombatMode/Libs/
      - id: selene
        name: selene
        entry: selene --config selene.toml
        language: system
        types: [lua]
        files: ^CombatMode/.*\.lua$
        exclude: ^CombatMode/Libs/
