---------------------------------------------------------------------------------------
--  Constants/FrameWatch.lua — CONSTANTS — auto-unlock frame / mount watchlists
---------------------------------------------------------------------------------------
--  What it does: Provides the default named-frame list, wildcard name groups (including
--  OPie rings), and vendor-mount spell IDs that Auto Cursor Unlock evaluates when deciding
--  whether freelook should stay off.
--  Architecture / how it works:
--    • FramesToCheck — static `_G[name]:IsVisible()` targets (bags, character, options,
--      CombatMode dialogs, etc.).
--    • Wildcard / group tables — prefix matches for dynamic frames; OPie rings feed the
--      FreeLook OPie rematch latch when visible.
--    • MountsToCheck — spell IDs for vendor mounts. Used as a fallback default when
--      seeding the user's mountsToUnlock DB list on first install.
--  Does not: Evaluate visibility, call MouselookStop, or own ShouldFreeLookBeOff.
--  Related: Core/FreeLook/AutoCursorUnlock.lua, Core/FreeLook/FreeLookController.lua,
--  UI/Options/Tabs/TabAutoCursorUnlock.lua, Constants/DatabaseDefaults.lua
---------------------------------------------------------------------------------------
local _, CM = ...

-- Default frames to check with a static name.
CM.Constants.FramesToCheck = {
  "AchievementFrame",
  "AddonList",
  "AuctionFrame",
  "AuctionHouseFrame",
  "BankFrame",
  "BattlefieldFrame",
  "BFAMissionFrame",
  "BonusRollFrame",
  "CalendarFrame",
  "CharacterFrame",
  "ChatMenu",
  "ChooseItemsFrame",
  "ClassTalentFrame",
  "ClassTrainerFrame",
  "ClickBindingFrame",
  "CoinPickupFrame",
  "CollectionsJournal",
  "CombatModeConfirmDialog",
  "CombatModeWelcomeDialog",
  "CombatModeOptionsFrame",
  "CommunitiesFrame",
  "ContainerFrame1",
  "ContainerFrame2",
  "ContainerFrame3",
  "ContainerFrame4",
  "ContainerFrame5",
  "ContainerFrame6",
  "ContainerFrame7",
  "ContainerFrame8",
  "ContainerFrame9",
  "ContainerFrame10",
  "ContainerFrame11",
  "ContainerFrame12",
  "ContainerFrame13",
  "ContainerFrame14",
  "ContainerFrame15",
  "ContainerFrame16",
  "ContainerFrame17",
  "ContainerFrameCombinedBags",
  "CovenantMissionFrame",
  "CovenantSanctumFrame",
  "DeathRecapFrame",
  "DressUpFrame",
  "DropDownList1",
  "DropDownList2",
  "DropDownList3",
  "DungeonReadyPopup",
  "EditModeManagerFrame",
  "EmoteMenu",
  "EncounterJournal",
  "ExpansionLandingPage",
  "FlightMapFrame",
  "FriendsFrame",
  "GameMenuFrame",
  "GarrisonCapacitiveDisplayFrame",
  "GenericTraitFrame",
  "GossipFrame",
  "GuildFrame",
  "GuildRegistrarFrame",
  "HelpFrame",
  "InspectFrame",
  "InspectPaperDollFrame",
  "InterfaceOptionsFrame",
  "InventoryManagerFrame",
  "ItemInteractionFrame",
  "ItemUpgradeFrame",
  "ItemTextFrame",
  "KeyBindingFrame",
  "LanguageMenu",
  "LFGDungeonReadyDialog",
  "LFDRoleCheckPopup",
  "LFGListInviteDialog",
  "LookingForGuildFrame",
  "MacroFrame",
  "MailFrame",
  "MajorFactionRenownFrame",
  "MerchantFrame",
  "OptionsFrame",
  "OrderHallMissionFrame",
  "OrderHallTalentFrame",
  "PaperDollFrame",
  "PetitionFrame",
  "PetPaperDollFrame",
  "PetRenamePopup",
  "PetStable",
  "PlayerChoiceFrame",
  "PlayerTalentFrame",
  "ProfessionsCustomerOrdersFrame",
  "ProfessionsFrame",
  "PVEFrame",
  "PVPMatchResults",
  "PVPMatchScoreboard",
  "PVPUIFrame",
  "QuestFrame",
  "QuestLogFrame",
  "QuestLogPopupDetailFrame",
  "QuestShareFrame",
  "QuickKeybindFrame",
  "RaidFrame",
  "ReadyCheckListenerFrame",
  "ReputationFrame",
  "ScriptErrorsFrame",
  "SkillFrame",
  "SettingsPanel",
  "SpellBookFrame",
  "SplashFrame",
  "StackSplitFrame",
  "StaticPopup1",
  "StaticPopup2",
  "StaticPopup3",
  "StaticPopup4",
  "StatsFrame",
  "SuggestFrame",
  "TabardFrame",
  "TalentFrame",
  "TalentTrainerFrame",
  "TaxiFrame",
  "TorghastLevelPickerFrame",
  "TradeFrame",
  "TradeSkillFrame",
  "TutorialFrame",
  "UnitPopup",
  "VoiceMacroMenu",
  "WardrobeFrame",
  "WorldMapFrame",
  "AccountantFrame",
  "ACP_AddonList",
  "ARKINV_Frame1",
  "AutoPotion_Template_Dialog",
  "BagnonFrameinventory",
  "BagnonInventory1",
  "ChessFrame",
  "ConnectFrame",
  "CosmosDropDown",
  "CosmosDropDownBis",
  "CosmosMasterFrame",
  "CraftFrame",
  "GamesListFrame",
  "GwCharacterWindow",
  "GwCharacterWindowsMoverFrame",
  "ImmersionFrame",
  "ImprovedErrorFrame",
  "LoXXXotFrame",
  "MAOptions",
  "MinesweeperFrame",
  "NxSocial",
  "OthelloFrame",
  "PetJournalParent",
  "SoundOptionsFrame",
  "StaticPopXXXup1",
  "TicTacToeFrame",
  "TotemStomperFrame",
  "UIOptionsFrame",
  "VideoOptionsFrame",
  "WantAds",
  "SubscriptionInterstitialFrame",
  "CinematicFrameCloseDialog",
  "MovieFrame",
  "HouseEditorFrame",
  "HousingDashboardFrame",
  "CatalogShopFrame",
  "HousingCornerstonePurchaseFrame",
  "ProfessionsBookFrame",
  "DelvesDifficultyPickerFrame",
  "Baganator_CategoryViewBackpackViewFrameblizzard",
  "Baganator_CategoryViewBackpackViewFramegw2_ui",
  "Baganator_CategoryViewBackpackViewFrame",
  "CombatModeReticleCVarEditor",
  "CombatModeChangelogFrame",
}

-- Default wildcard patterns and known candidates by prefix.
CM.Constants.WildcardFramesToMatch = { "OPieRT" }

CM.Constants.WildcardFrameCandidates = {
  OPieRT = { "OPieRT", "OPieRT-1", "OPieRT-2", "OPieRT-3" },
}

-- Runtime-discovered wildcard frame names.
CM.Constants.WildcardFramesToCheck = {}

-- Vendor mounts to force UnlockFreeLook.
CM.Constants.MountsToCheck = {
  61447, -- Traveler's Tundra Mammoth
  122708, -- Grand Expedition Yak
  264058, -- Mighty Caravan Brutosaur
  465235, -- Trader's Gilded Brutosaur
  457485, -- Grizzly Hills Packmaster
}
