param()

$ErrorActionPreference = "Stop"

Write-Host "== CombatMode contributor helper scripts =="
Write-Host ""
Write-Host "pwsh ./scripts/dev-check.ps1"
Write-Host "  - Validates local toolchain readiness (stylua, selene, pre-commit)"
Write-Host "  - Confirms required config files exist"
Write-Host ""
Write-Host "pwsh ./scripts/lint-changed.ps1"
Write-Host "  - Runs pre-commit on changed addon-owned Lua files"
Write-Host "  - Excludes vendored libs under CombatMode/Libs/"
Write-Host ""
Write-Host "pwsh ./scripts/sync-changelog-to-lua.ps1"
Write-Host "  - Copies CombatMode/CHANGELOG.md → Config/ConfigChangelogData.lua (in-game viewer)"
Write-Host ""
Write-Host "Useful direct commands:"
Write-Host "  pre-commit run --files <changed files>"
Write-Host "  pre-commit run --all-files   (release prep / maintainer request)"
Write-Host "  stylua --check <paths>       (debug)"
Write-Host "  selene --config selene.toml <paths>   (debug)"
Write-Host ""
Write-Host "Reference docs:"
Write-Host "  CONTRIBUTING.md"
Write-Host "  TESTING.md"
Write-Host "  RELEASE.md"
